"""
Regras de classificação por palavras-chave.

Arquivo gerado a partir do notebook classificadorTeste.ipynb (células 0, 1 e 2),
sem alterar as regras. Para ajustar uma categoria, edite os dicionários abaixo.
"""
import re
import unicodedata


def normalizar_texto(texto):
    texto = str(texto).lower()
    texto = unicodedata.normalize("NFD", texto)
    texto = "".join(c for c in texto if unicodedata.category(c) != "Mn")
    texto = re.sub(r"[^a-z0-9\s]", " ", texto)
    texto = re.sub(r"\s+", " ", texto)
    return texto.strip()


CATEGORIAS_ESPECIFICAS = {
    1: "Aquisição de Alimentos e Gêneros Alimentícios",
    2: "Aquisição de Combustíveis e Lubrificantes",
    3: "Aquisição de Equipamentos e Materiais Permanentes",
    4: "Aquisição de Material de Expediente",
    5: "Aquisição de Material de Limpeza e Higienização",
    6: "Aquisição de Material Médico-Hospitalar",
    7: "Aquisição de Medicamentos",
    8: "Aquisição de Mobiliário",
    9: "Aquisição de Peças e Acessórios",
    10: "Contratação de Obras e Serviços de Engenharia",
    11: "Contratação de Serviços Administrativos",
    12: "Contratação de Serviços de Consultoria",
    13: "Contratação de Serviços de Educação e Capacitação",
    14: "Contratação de Serviços de Limpeza e Conservação",
    15: "Contratação de Serviços de Locação",
    16: "Contratação de Serviços de Manutenção",
    17: "Contratação de Serviços de Saúde",
    18: "Contratação de Serviços de Tecnologia da Informação",
    19: "Contratação de Transporte Escolar",
    20: "Contratação de Serviços de Publicidade e Comunicação",
    21: "Alienação de bens",
    22: "Outros"
}



ORDEM_COMPRAS = [7, 6, 2, 5, 1, 9, 8, 4, 18, 3, 21]

ORDEM_SERVICOS = [19, 17, 10, 20, 12, 13, 14, 15, 16, 18, 11, 21]


REGRAS_COMPRAS = {
    # 1 - Aquisição de Alimentos e Gêneros Alimentícios
    1: r"\b(genero alimenticio|genero de alimentacao|generos alimenticios|genero alimenticios|generos de alimentacao|alimentacao escolar|alimentacao|merenda|pnae|agricultura familiar|alimentos?|cesta basica|kit alimentacao|refeicoes?|quentinha|coffee break|coffe break|lanches?|buffet|hortifruti|hortifrutigranjeir|frutas?|verduras?|legumes?|arroz|feijao|macarrao|leite|carne|frango|peixe|ovos?|proteinas?|panificacao|paes?|bolo|biscoito|pao|pao de coco|farinha|acucar|oleo de soja|sal|polpa de fruta|agua mineral|cafe|cafe torrado|cafe moido|agua adicionada de sais|agua potavel|garrafao de agua|dieta enteral|suplemento alimentar|kit lanche|kit pascoa|kits de pascoa|aquisicao de agua|agua mineral natural|fornecimento de alimentacao|alimentacao ii|generos de de alimentacao|generos alimenticio|aquisicao generos alimenticio|cereais|arp cereais|racao|racoes|suplemento nutricional|gramas do item|criancas expostas ao hiv)\b",
    # 2 - Aquisição de Combustíveis e Lubrificantes
    2: r"\b(combustiveis?|gasolina|diesel|oleo diesel|etanol|aquisicao de combustivel|combustivel|alcool combustivel|lubrificantes?|oleo lubrificante|arla|graxas?|querosene|glp|gas liquefeito|gas engarrafado|gas cozinha|botij(ao|oes)|recarga de gas|vasilhames?|gas de cozinha|gas e outros materiais engarrafados|gas engarrafao|gas 13kg|gas de cozinha 13 kg|gas de cozinha 13kg|gas|pilhas alcalinas|pilhas?|baterias?)\b",
    # 3 - Aquisição de Equipamentos e Materiais Permanentes
    3: r"\b(equipamentos?|material permanente|materiais permanentes|bens permanentes|eletrodomesticos?|ar condicionado|condicionador de ar|bebedouros?|geladeiras?|freezers?|fog(ao|oes)|microondas|televisores?|tv|projetores?|caixa de som|maquinas?|tratores?|implementos? agricolas?|equipamentos? agricolas?|veiculos?|automoveis?|ambulancias?|motocicletas?|tablets?|aparelhos?|eletroeletronicos?|equipamento de audio|audio video|audiovisual|condicionadores de ar|lampadas? led|luminarias?|material eletrico|material eletronico|eletrico e eletronico|estabilizadores?|nobreaks?|no break|lavadora de alta pressao|fritadeira|air fryer|motor eletrico|portao industrial|andaimes?|plataforma para andaime|rodizio simples|equipamentos? de protecao|cameras? de seguranca|camera de seguranca|relogio digital|controlador de acesso|equipamentos? de seguranca|perifericos|kit biometrico|leitor biometrico|biometrico|aparelho de ar condicionado|splits?|tipo split|climatizadores?|ventiladores?|bebedouro industrial|bombas? submersas?|bomba submersa|material de protecao e seguranca|protecao e seguranca|sinalizacao de transito|material de sinalizacao de transito|material de sinalizacao|semaforos?|cones de sinalizacao|material para audio e video|audio e video|ferramentas? e utensilios|ferramentas?|utensilios|chaleira eletrica|areninhas?|placar eletronico|material hidraulico|materiais hidraulicos|aquisicoes de materiais de construcao|hidraulicos|materiais de construcao|material civil|bens imoveis e instalacoes|porta de vidro|fechadura biometrica|catracas?|catracas para controle|camera de alta resolucao|cameras?|balanca antropometrica|balanca pediatrica|balanca eletronica|extintores?|roçadeiras?|rocadeiras?|roçadeira|rocadeira|motor de popa|trena eletronica|workstation|desktop|desktops|monitor de video|monitores?|tvs led|tv led|ventilador de parede|escada de aluminio|ancinhos?|enxadoes?|enxadas?|foices?|facoes?|machados?|chibancas?|cavadeiras?|sementes|mudas de plantas|insumos agricolas|quintais produtivos|barraca|barracas|traves de futsal|postes mastros|placas em acos inox|plaquetas de identificacao|leitores de codigo de barras|radiofrequencias|fones de ouvido|hubs para carregamento|purificadores de agua|filtros para os purificadores|material de refrigeracao|materiais para estruturacao)\b",
    # 4 - Aquisição de Material de Expediente educativo exportivo
    4: r"\b(material de expediente|expediente|papelaria|materiais escolares|kits e materiais escolares|material escolar|material didatico|material educativo|instrumentos musicais|materiais de ensino religioso|instrumento musical|material pedagogico|materiais esportivos|material esportivo|artigos? esportivos?|equipamentos? esportivos?|bola|bolas|rede esportiva|cones?|coletes?|apito|trofeus?|medalhas?|papel a4|papel alcalino|canetas?|lapis|borrachas?|cadernos?|cartolinas?|pastas?|grampeadores?|grampos?|clips|envelopes?|toner|cartuchos?|tinta para impressora|livros?|cracha|crachas|cordoes|pincel|pinceis|quadro branco|marca texto|corretivo|brinquedos?|material de copa|material de cozinha|material de copa e cozinha|copa e cozinha|utensilios de cozinha|utensilios domesticos|copo|copos|prato|pratos|talher|talheres|colher|colheres|garfo|garfos|faca|facas|panela|panelas|bandeja|bandejas|garrafa termica|garrafas termicas|xicaras?|canecas?|descartaveis?|material de acondicionamento|material de embalagem|acondicionamento e embalagem|embalagens?|fardamentos?|fardamento escolar|uniformes?|uniformes esportivos|camisas?|camisetas?|camisa gola polo|conjunto infantil|kit bebe|kit bebes|kit natalidade|enxoval|fraldas descartaveis|mochilas?|bolsas escolares|tecidos?|material serigrafico|aquisicao de vestuarios em geral|aquisicao de materiais esportivos|material destinada distribuicao gratuita|tabelas? de basquete|basquete|sapatilhas?|collants?|saias?|meias?|shorts?|material de ballet|ballet|bobinas? termicas?|bobina termica|giz de cera|perfurador|tesouras?|lapiseira|apontador|regua|almoxarifado|fita adesiva|papel madeira|papel oficio|papel reciclado|papel a3|kit escolar|kits de formatura|kits pedagogicos|capelo|beca|bandeiras|flamulas|insignias|pranchetas|confeccao de pranchetas|folderes|aquisicao de folderes|apostilas|confeccao de apostilas|capas? e contra capas? de prontuario|capa e contra capa de prontuario|brindes|material de consumo escritorio|escritorio|material de consumo fita adesiva|material de consumo para atender as necessidades da coads|material de consumo para atender a coads|material de consumo para atender as necessidades da srnor|material de consumo para atender as necessidades da srsul|coads|srnor|srsul)\b",
    # 5 - Aquisição de Material de Limpeza e Higienização
    5: r"\b(material de limpeza|limpeza e higienizacao|produtos? de limpeza|desentupidor sanitario|flanela|saco para lixo|escova|material de higiene|higiene pessoal|aquisicao de materiais de consumo da linha de higiene e limpeza|higienizacao|saneantes?|detergentes?|desinfetantes?|agua sanitaria|sab(ao|oes)|sabonetes?|alcool gel|alcool 70|papel higienico|papel toalha|vassouras?|rodos?|baldes?|esponjas?|lixeiras?|saco de lixo|sacos de lixo|fraldas?|absorventes?|consumo limpeza|material consumo limpeza|produtos? higienicos|material higienico|higienicos|saude intima|absorvente higienico|materiais de limpeza|materal de limpeza|material descartavel|descartavel|pedra sanitaria|sacos para lixo|aquisicao material limpeza|material de consumo de limpeza|limpezaeemti)\b",
    # 6 - Aquisição de Material Médico-Hospitalar
    6: r"\b(material medico|material hospitalar|medico hospitalar|materiais medicos|materiais hospitalares|material odontologico|instrumentais odontologicos|odontologico|insumos? hospitalares?|equipamentos? hospitalares?|luvas? cirurgicas?|mascaras? cirurgicas?|seringas?|agulhas?|gazes?|ataduras?|cateter(es)?|sondas?|eletrodos?|testes? rapidos?|reagentes?|material laboratorial|laboratorio|oxigenio medicinal|epis? hospitalares?|dieta enteral|nutricao enteral|nutrison|equipo|soro macrogotas|insumos laboratoriais|insumo laboratorial|material odontologicos|materiais odontologicos|odontologicos|analisador genetico|material ambulatorio|ambulatorio|unidades de saude.*sesa|hospital geral|instrumental cirurgico|instrumentais cirurgicos|gas oxigenio|oxigenio gasoso|material quimico|reagentes quimicos|insumos quimicos|malha tubular|fixacao de curativo|curativo|tampa lacre|vial de headspace|toxicologia forense|nucleo de toxicologia|coordenadoria de analises laboratoriais|calf|faculdade de medicina|departamento de odontologia|hcasg|materiais medico hospitalares|materiais medico hospitais|dispositivos para estomias|estomias intestinais|fistulas entericas|campo operatorio|campo operatorio fenestrado|campo impermeavel|fronha de mayo|hemostatico|tela absorvivel|surgicel|mascaras de respirador|placa de pericardio|pericardio bovino|orteses|proteses|opm|meios auxiliares de locomocao|aventais e protetores|hospitalares aventais|dome|kit para monitorizacao invasiva|monitorizacao invasiva)\b",
    # 7 - Aquisição de Medicamentos
    7: r"\b(medicamentos?|farmacos?|farmaceutic[oa]s?|material farmacologico|remedios?|comprimidos?|capsulas?|antibioticos?|analgesicos?|anti inflamatorios?|soro fisiologico|insulina|vacinas?|psicotropicos?|toxina botulinica|botox|mg ml|solucao injetavel|frasco ampola|po liofilizado|liofilizado|injetavel|ampola|comprimido|dose|fluoruracila|paracetamol|dipirona|amoxicilina|ibuprofeno|cloreto de sodio|demandas judiciais|sulfato de polimixina|neomicina|hidrocortisona|solucao otologica|anestesico local|mepivacaina|epinefrina|tubetes|ampolas?)\b",
    # 8 - Aquisição de Mobiliário
    8: r"\b(mobiliarios?|moveis?|mesa|mesas|cadeira|cadeiras|armario|armarios|estante|estantes|biro|carteira escolar|carteiras escolares|conjuntos de carteiras|longarinas?|gaveteiros?|balc(ao|oes)|prateleiras?|sofas?|poltronas?|colch(ao|oes)|bercos?|cortinas?|persianas?|colchoes?|colchao|berco|armarios escolares)\b",
    # 9 - Aquisição de Peças e Acessórios
    9: r"\b(pecas?|acessorios?|pneus?|camara de ar|baterias? automotivas?|filtro de oleo|pastilhas? de freio|discos? de freio|amortecedores?|correias?|rolamentos?|velas? de ignicao|pecas automotivas|pecas para veiculos|pecas de reposicao|componentes?)\b",
    
    18: r"\b(informatica|tecnologia da informacao|material grafico|grafico|graficos|tic|software|sistemas?|licenca de software|licenciamento de software|computadores?|notebooks?|impressoras?|servidores?|rede de computadores|internet|link dedicado|fibra optica|suporte tecnico|desenvolvimento de sistema|hospedagem|website|site|portal|backup|firewall|certificados? digitais?|token|telefonia ip|plataforma whatsapp|dataprev|tableau|cessao de uso de software|processamento de dados|proc de dados|proc dados|material de processamento de dados|material de proc de dados|material de proc dados|lgpd|lei geral de protecao de dados|certificado digital|emissao de certificado digital|videoconferencia|solucao de videoconferencia|adobe creative cloud|creative cloud|solucao baseada em tecnologia|tecnologia em nuvem|processo digital|implantacao do processo digital|implementacao e monitoramento|organizadores? de cabos|cordao optico|materiais de ti|cabos espiral|cabo de rede|switch|roteador|access point|hd externo|ssd|memoria ram|cartao de memoria|plataforma web|processos eletronicos|sistema web|plataforma digital|material de processamento|seguranca da informacao|cabeamento logico|biometria facial|reconhecimento facial|qr code|catracas para controle|cabeca de impressao|fotocondutor|gabinete para computador|processador|socket|cooler|suprimento de informaticas|suprimento de informatica|mouse|desktop|desktops|workstation|monitor de video|leitor de codigo de barras|radiofrequencias|material de consumo de informatica|hubs para carregamento|drones|dji mavic|hdmi|fone bluetooth)\b",
}


REGRAS_SERVICOS = {
   
   # 10 - Contratação de Obras e Serviços de Engenharia
    10: r"\b(obras?|engenharia|servicos? de engenharia|construcao|reforma|ampliacao|adaptacao de ambiente|pavimentacao|recuperacao de estrada|estrada vicinal|calcamento|drenagem|saneamento|urbanizacao|pracas?|passagem molhada|poco profundo|adutora|barragem|revitalizacao|requalificacao|construcao civil|subestacao|ubsi|unidade basica de saude|rodovias?|picarramento|iluminacao publica|modernizacao do parque de iluminacao|parque de iluminacao|infraestrutura|instalacao de isolamento acustico|isolamento acustico|servico de instalacao|instalacao eletrica|subestacao abaixadora|elaboracao de projetos de engenharia|demolicao|demolicao do predio|servicos demolicao|construcao de quadra|recuperacao de coberta|servico de recuperacao de coberta|coberta|terraplanagem|pavimentacao em pedra|reforma predial|recapeamento|passagens molhadas|passagem molhada|sinalizacao horizontal|sinalizacao vertical|tacha refletiva|tachao refletivo|abastecimento dagua|abastecimento de agua|melhorias na estrada|retoques e pintura|retelhamento|telha ceramica|substituicao de telhas|quadra de esportes|recuperacao civil eletrica|restauracao da ce|servico de adequacao|adequacao do setor|adequacao do novo imovel|servicos de instalacao de cabeamento logico e eletrico|cabeamento logico e eletrico|substituicao de piso vinilico|material hidraulico e civil|instalacao de divisoria|divisoria em placas de gesso|iluminacao do campo de futebol|execucao de acoes integradas de educacao em saude ambiental)\b",

    # 11 - Contratação de Serviços Administrativos
    11: r"\b(servicos? administrativos?|apoio administrativo|contratacao de pessoa fisica|contratacao de pessoa juridica|gestao administrativa|organizacao de documentos|gestao documental|digitalizacao|protocolo|recepcao|secretaria executiva|servicos? auxiliares|apoio operacional|terceirizacao de mao de obra|mao de obra|dedicacao exclusiva|agente administrativo|estagio|agente de integracao|auxiliar administrativo|fornecimento de mao de obra|controlador de acesso|porteiro|vigilancia|seguranca patrimonial|suporte administrativo|suporte financeiro|agenciamento de viagens|passagens aereas|bilhetes|servicos funerarios|funerarios|beneficios eventuais|servicos de terceiros|terceiros|servicos gerais|servicos operacionais|auxiliar de servicos gerais|cozinheira|recepcionista|assistente de apoio a gestao|almoxarife|interprete de libras|fornecer agua tratada|fornecimento de agua tratada|abastecimento de agua|cagece|saae|servico autonomo de agua|contrato direitos humanos e protecao social|recursos humanos|lote unico recursos humanos|apoio a gestao do suas|programa bolsa familia|cadastro unico|visitador do programa crianca feliz|entrevistador do cadastro unico|acolhimento de idosa|instituicao de longa permanencia|avaliacao de bens imoveis|armazenagem de mercadorias|deposito|facilidades portuarias|manobra militares|seguro patrimonial|apolice de seguro patrimonial|fornecimento de agua e coleta de esgoto|coleta de esgoto|concessao de uso|concessao de uso a titulo oneroso|restaurante|seguranca publica|apoio a seguranca publica|monitoramento eletronico|gestao da mobilidade urbana|contrato seguranca|contrato dhps|contrato social|contrato do saldo total social|contrato do saldo total esporte|contrato juventude|contrato pesca|contrato fundeb|contrato enio|contrato tania|contrato 03|contrato 09|contrato 11|chromos|bf de meneses|santa cruz|km rental|eclipse|coopsan|agrinort|coopasi|governanca|fazenda|gabinete|procuradoria|ouvidoria|mulher|ama)\b",

    # 12 - Contratação de Serviços de Consultoria
    12: r"\b(consultoria|consultorias|assessoria|assessorias|assessoramento|consultoria tecnica|consultoria especializada|assessoria tecnica|assessoria especializada|servicos? tecnicos especializados|prestacao de servicos de assessoria|servicos? de assessoria|assessoria em contabilidade|contabilidade publica|servicos? contabeis|servico contabil|contabil|contabeis|contabilidade|natureza tecnica e singular|notoria especializacao|auditoria|pericia|elaboracao de projeto|estudo tecnico|diagnostico|planejamento estrategico|plano de contratacoes anual|pca|processos de compras publicas|licitacoes e contratos|assessoria juridica|consultoria juridica|advocacia|servicos juridicos|servicos profissionais contabilidade|servicos tecnicos profissionais|tecnicos profissionais|consultor individual|consultor a individual|cultura organizacional|odr|online dispute resolution|compras publicas|concurso publico|concursos publicos|processo seletivo|processo seletivo de estudantes|planejar organizar e executar|organizacao planejamento e execucao|avaliacao de bens imoveis|compliance|transparencia publica)\b",

    # 13 - Contratação de Serviços de Educação e Capacitação
    13: r"\b(capacitacao|treinamentos?|cursos?|oficinas?|palestras?|seminarios?|formacao continuada|jornada pedagogica|educacao permanente|instrutor|coordenador|Coordenador(a)|instrutores?|professores?|material pedagogico|kits pedagogicos|projeto pedagogico|assessoria pedagogica|servicos educacionais|aulas?|facilitador|educador social|orientador social|scfv|organizacao social qualificada.*educacao|educacao infantil|mantenedoras educacao infantil|mantenedoras de educacao|entidades comunitarias.*educacao|chamamento publico.*educacao|assistente em educacao inclusiva|aei|educacao inclusiva|capacitacoes para familias|senat|programa de educacao financeira|empreendedorismo|projeto de vida|ensino fundamental|inscricoes presenciais|participacao de profissionais|congresso|jornada imersiva|gestao publica|inscricoes para participacao|corrida da policia rodoviaria|formacao de condutores|categoria a e b|educacao municipal|educacao em saude ambiental)\b",

    # 14 - Contratação de Serviços de Limpeza e Conservação
    14: r"\b(servicos? de limpeza|limpeza predial|conservacao predial|servicos? de conservacao|dedetizacao|desinsetizacao|desratizacao|capinacao|varricao|jardinagem|podacao|coleta de lixo|coleta de residuos|limpeza urbana|higienizacao de ambientes|conservacao e limpeza|asseio|roco|rocagem|coleta transporte e destinacao|residuos solidos|limpeza publica|tratamento e conservacao da piscina|limpeza tratamento e conservacao|tratamento de piscina|conservacao da piscina|servico para limpeza|limpeza de piscina|limpeza e conservacao|limpeza e conservacao da ete|limpeza da caixa d agua|potabilidade|retirada de dejetos|retiradas de dejetos|fossas|sumidouros|detritos|capina|desgalhamento|poda|controle ambiental|limpeza para subsede)\b",

    # 15 - Contratação de Serviços de Locação
    15: r"\b(locacao|locacoes|aluguel|alugueis|locar|arrendamento|cessao de uso|locacao de veiculo|frota de veiculos|locacao de maquinas|locacao de equipamentos|locacao de imovel|aluguel de imovel|locacao de sistema|locacao de impressora|locacao de estrutura|tendas?|banheiros? quimicos?|palco|palcos|som e iluminacao|carreta tematica|trem maria fumaca|montagem operacao e desmontagem|fornecimento montagem operacao desmontagem|imovel tipo residencia|imovel composto|locacao de predio|aluguel social|km rental|rental|espaco fisico)\b",

    # 16 - Contratação de Serviços de Manutenção
    16: r"\b(manutencao|manutencoes|conserto|reparo|reparos|assistencia tecnica|revisao|corretiva|preventiva|manutencao preventiva|manutencao corretiva|manutencao de veiculo|manutencao de equipamentos|manutencao predial|recarga de toner|recarga de cartucho|servicos mecanicos|mecanica|lanternagem|borracharia|lavagem de veiculos|instalacao de ar condicionado|instalacoes de ares condicionados|matutencao|manutencao em ventiladores|manutencao de ventiladores|conserto de ventiladores|instalacao de equipamentos|instalacao e manutencao|recarga dos extintores|recarga de extintores|recarga extintores|manutencao de extintores)\b",

    # 17 - Contratação de Serviços de Saúde
    17: r"\b(servicos? de saude|procedimentos? medicos?|exames? laboratoriais?|servicos laboratoriais|exames? por imagem|consulta medica|consultas medicas|plantoes? medicos?|servicos? medicos?|servicos? odontologicos?|fisioterapia|psicologia|fonoaudiologia|atendimento medico|hospitalar|cirurgias?|mamografia|radiologia|perfusionista|auxiliar de saude|profissional de saude|clinica|pacientes?|samu|servico de atendimento movel de urgencia|terapeuta ocupacional|terapeuta ocupacioanl|urgencia|regulacao regional|casa de apoio a saude indigena|casai|credenciar pessoas fisicas.*saude|credenciamento de pessoas fisicas.*saude|plantao.*hospital|medicos.*plantao|oftalmologicos?|oftalmologicas?|lentes oftalmicas|armacoes e lentes|protese total|protese dentaria|castracao cirurgica|caes e felinos|servicos profissionais destinados ao atendimento das demandas da secretaria municipal de saude|profissionais destinados ao atendimento.*saude|contrato saude|servicos oftalmologicos|exames microscopia|microscopia otica|imunofluorescencia|microscopia eletronica|saude ambiental|contratualizacao.*hiv|secretaria de saude)\b",

    # 18 - Contratação de Serviços de Tecnologia da Informação
    18: r"\b(informatica|tecnologia da informacao|material grafico|grafico|graficos|tic|software|sistemas?|licenca de software|licenciamento de software|computadores?|notebooks?|impressoras?|servidores?|rede de computadores|internet|link dedicado|fibra optica|suporte tecnico|desenvolvimento de sistema|hospedagem|website|site|portal|backup|firewall|certificados? digitais?|token|telefonia ip|plataforma whatsapp|dataprev|tableau|cessao de uso de software|processamento de dados|proc de dados|proc dados|material de processamento de dados|material de proc de dados|material de proc dados|lgpd|lei geral de protecao de dados|certificado digital|emissao de certificado digital|videoconferencia|solucao de videoconferencia|adobe creative cloud|creative cloud|solucao baseada em tecnologia|tecnologia em nuvem|processo digital|implantacao do processo digital|implementacao e monitoramento|organizadores? de cabos|cordao optico|materiais de ti|cabos espiral|cabo de rede|switch|roteador|access point|hd externo|ssd|memoria ram|cartao de memoria|plataforma web|processos eletronicos|sistema web|plataforma digital|material de processamento|seguranca da informacao|cabeamento logico|biometria facial|reconhecimento facial|qr code|catracas para controle|cabeca de impressao|fotocondutor|gabinete para computador|processador|socket|cooler|suprimento de informaticas|suprimento de informatica|mouse|desktop|desktops|workstation|monitor de video|leitor de codigo de barras|radiofrequencias|material de consumo de informatica|hubs para carregamento|drones|dji mavic|hdmi|fone bluetooth)\b",

    # 19 - Contratação de Transporte Escolar
    19: r"\b(transporte escolar|transporte de alunos?|transporte dos alunos?|transporte universitario|conducao de alunos?|rotas? escolares?|veiculo escolar|onibus escolar|motorista escolar|alunos da rede|transporte individual de passageiros|taxi)\b",

    # 20 - Contratação de Serviços de Publicidade e Comunicação
    20: r"\b(publicidade|propaganda|comunicacao|divulgacao|marketing|campanha publicitaria|midia|radio|radiodifusao|carro de som|sonorizacao|filmagem|fotografia|transmissao|live|streaming|redes sociais|identidade visual|impressao grafica|servicos? graficos?|material grafico|eventos?|organizacao de eventos?|festividades?|festa|festas|homenagens?|cerimonial|mestre de cerimonia|decoracao|ornamentacao|estrutura para eventos?|servicos? de eventos?|show artistico|apresentacao artistica|atracao musical|producao musical|conteudo audiovisual|audiovisual|emancipacao politica|publicacoes legais|jornal de grande circulacao|diario oficial|adesivo institucional|grafica|confeccao de adesivo|carimbos?|material institucional personalizado|publicacoes oficiais|publicacao oficial|show da atracao|atracao|artista|dj|carnaval|regata|paquetes|sessoes solenes|titulos honorificos|papel couche|confeccao de titulos|botons?|chaveiros?|adesivos personalizados|carteiras funcionais|cestas de aniversario|homenagear|data natalicia|producao artistica|apresentacao na regata|apresentacao musical|materiais graficos|material grafico e afins|sinalizacao visual|material de sinalizacao visual|afins graficos|serigrafia|placas de identificacao|placas de inauguracao|equipamento artistico|equimamento artistico|profissional do setor artistico|atividades da reuniao ampliada|prestacao dos servicos fotograficos|servicos fotograficos|fotograficos|contrato cultura|contarto cultura|secult|turismo|contrato turismo|bandeiras|flamulas|insignias|placas em acos inox|folderes|carteiras funcionais|banda|bandas|contratacao de empresa especializada em servicos de refeicoes)\b"
}
